### ISSUE TITLE
Custom element doesn't exist: floorplan-card

### ISSUE THREAD

**Issue by lujiashun1** [ExperienceLovelace/lovelace-floorplan#45]
![image](https://user-images.githubusercontent.com/6397951/100819514-49e66f80-3487-11eb-9501-728dd7a3d6e1.png)
1、copy dist/floorplan-card.js to www/lovelace-floorplan folder
![image](https://user-images.githubusercontent.com/6397951/100820505-58ce2180-3489-11eb-80ca-41c4abfbf4c4.png)
2、add this module to resources
![image](https://user-images.githubusercontent.com/6397951/100820356-f83ee480-3488-11eb-8a92-d1868affd8aa.png)
3、copy these four files to this folder
![image](https://user-images.githubusercontent.com/6397951/100820652-9c289000-3489-11eb-8668-1e0aa580fdbd.png)
4、add entities and automation
![image](https://user-images.githubusercontent.com/6397951/100820739-d5610000-3489-11eb-8783-4be435a99635.png)
5、copy the code to Card Configuration
but it did not work  
![image](https://user-images.githubusercontent.com/6397951/100820838-16f1ab00-348a-11eb-8c95-783ffd176e47.png)
how to solve this problem .Thanks

**Comment by lujiashun1** [comment]
![image](https://user-images.githubusercontent.com/6397951/100841259-00f7e080-34b2-11eb-89c2-6a0f3184b219.png)
install it in HACS,just like this,can not display the picture below
![image](https://user-images.githubusercontent.com/6397951/100841502-5b913c80-34b2-11eb-99b1-03b6405b0f5a.png)

**Comment by lujiashun1** [comment]
![image](https://user-images.githubusercontent.com/6397951/100841638-854a6380-34b2-11eb-8a79-e56421d7cae2.png)

**Comment by exetico** [comment]
Hi @lujiashun1 

I'm trying to find out, what the real problem is.

Have you secured to add floorplan as a Lovelace resource? You also need to refresh HA's Lovelave interface, so it's using the resources, too. Else, you'll have the Lovelave-ressources served through cached data.

Please provide a few more details about what the actual problem is, if you're able to do so. If the language is a problem, you're welcome to try with translate. 

More information about good details, and problem-details, can be found [here](http://xyproblem.info/).
